### ISSUE TITLE
P1: Video link fails for youtube link

### ISSUE THREAD

**Issue by muralihr** [janastu/pondy-heritage-web#51]
Youtube link does not work !
Only urls with total like to mp4 files seem to work.
enable all video links to work 
Is there a way to check that the links are proper - before showing on the map?

**Comment by salus-sage** [comment]
Hi,
Since we were using the html5 web player, which cannot play videos from 3rd party service, 
Marking this as enhancement for V0.0.5 milestone. 
However, further we should also determine how many such third party services we should be supporting.

**Comment by salus-sage** [comment]
moving to P1 - as client has to upload videos for the release day

**Comment by salus-sage** [comment]
Issue resolved
