### ISSUE TITLE
Corrupt data from api/mapp

### ISSUE THREAD

**Issue by salus-sage** [janastu/pondy-heritage-web#74]
theres atleast 41 points with user: "anonymousUser" 
{"type":"Feature","properties":{"marker-symbol":"camera","appname":"PondyMap","marker-color":"#ff8888","description":"  \r\npost","title":"test","category":"Village Life","uploadTime":"29-06-2016 00:45:51","marker-size":"small","mediatype":"IMAGE","groupname":"Intach Group",**

**> "user":"anonymousUser"**

**,"url":"http://pondy.openrun.com:8080//heritagedocs/list/heritageimages//bustour.png"},"geometry":{"type":"Point","coordinates":[79.698600769,12.006748772]},"id":"137"}

**Comment by salus-sage** [comment]
is dependent on data - to provide edit and delete feature to user.

**Comment by muralihr** [comment]
Thanks Bhanu ! 
This was a hidden bug - went unnoticed for a long time -fixing the same -
