### ISSUE TITLE
Server down and unbale to get the code to deploy

### ISSUE THREAD

**Issue by muralihr** [janastu/pondy-heritage-web#91]
upstart log has fibers install error.
Did not move any files or code

**Comment by salus-sage** [comment]
# Steps taken to debug and documentation of changes made on server.

    Sudo su pondy

Found 2 directories, **pondy-heritage-web** and **pondy-heritage-back** 
@muralihr any reasons for moving the pondy deployed code?

in pondy-heritage-web branch "live..." code build had an error

So, i tried to check **pondy-heritage-back** which had the branch "V0.0.2" which i was familiar with and pulled recent changes and built for browser. 
new bundle directory is at built from  **pondy-heritage-back** branch "V0.0.2"

    pondy@ubuntu/~$pondy-deploy-zip
Installed npm modules, manually installed fibers.
upstart log is empty, but nginx 502 bad gateway error is reported on browser.

**Comment by salus-sage** [comment]
I see a new error in upstart log on mongodb
@muralihr are you trying something?

**Comment by salus-sage** [comment]
Issue Resolved.
Solution: Instead of using the pondy.conf to run the node server, 
@muralihr used [nohup](https://en.wikipedia.org/wiki/Nohup) to run the meteor production command in background. 
    meteor --settings settings.json --port 8085 --production
